# Generated by Django 4.2.2 on 2023-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntresetedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('icons', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserExpected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('icons', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('icons', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('icons', models.ImageField(upload_to='')),
            ],
        ),
    ]
