# Generated by Django 4.2.2 on 2023-11-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intresetedin',
            options={'verbose_name': 'USER INTRESTED IN', 'verbose_name_plural': 'USER INTRESTED IN'},
        ),
        migrations.AlterModelOptions(
            name='userexpected',
            options={'verbose_name': 'USER EXPECTED TO', 'verbose_name_plural': 'USER EXPECTED TO'},
        ),
        migrations.AlterModelOptions(
            name='userpreferance',
            options={'verbose_name': 'USER PREFERANCE', 'verbose_name_plural': 'USER PREFERANCE'},
        ),
        migrations.AlterModelOptions(
            name='userprofession',
            options={'verbose_name': 'USER PROFESSION', 'verbose_name_plural': 'USER PROFESSION'},
        ),
    ]
