# Generated by Django 4.2.2 on 2023-11-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSettings', '0003_alter_intresetedin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intresetedin',
            options={'verbose_name': 'User Intrested', 'verbose_name_plural': 'User Intrested'},
        ),
    ]
