# Generated by Django 4.2.2 on 2023-11-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0003_remove_user_profile_userpreferance_and_more'),
        ('AppSettings', '0005_alter_intresetedin_icons_alter_userexpected_icons_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferance',
        ),
    ]
