# Generated by Django 4.2.2 on 2023-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_Behaviours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match_table',
            options={'verbose_name': 'Matches', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='swipes_table',
            options={'verbose_name': 'Swipes', 'verbose_name_plural': 'Swipes'},
        ),
        migrations.AddField(
            model_name='match_table',
            name='is_mutual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
