# Generated by Django 4.2.2 on 2023-11-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_Behaviours', '0003_pushnotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNotifications',
        ),
    ]
