# Generated by Django 4.2.2 on 2023-11-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_Behaviours', '0005_userstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name': 'User Status', 'verbose_name_plural': 'User Status'},
        ),
    ]
