# Generated by Django 4.2.7 on 2023-11-24 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_enabled', models.BooleanField(default=True, null=True)),
                ('theme', models.CharField(blank=True, default='Light', max_length=255, null=True)),
                ('privacy_level', models.CharField(blank=True, default='Private', max_length=255, null=True)),
                ('language', models.CharField(blank=True, default='ENG', max_length=255, null=True)),
                ('email_notification_enabled', models.BooleanField(default=True)),
                ('push_notification_enabled', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('report_sub_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('report_note', models.TextField(blank=True, null=True)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('reported_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_user_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reported User',
                'verbose_name_plural': 'Report Users',
            },
        ),
        migrations.CreateModel(
            name='BlockedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateField(default=django.utils.timezone.now)),
                ('blocked_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_blocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Users',
                'verbose_name_plural': 'Blocked Users',
            },
        ),
    ]
