# Generated by Django 4.2.2 on 2023-11-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppSettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('canShowGender', models.BooleanField(default=True)),
                ('canShowUserProfession', models.BooleanField(default=True)),
                ('canShowUserPreferance', models.BooleanField(default=True)),
                ('canShowUserIntresetedIn', models.BooleanField(default=True)),
                ('canShowUserExpected', models.BooleanField(default=True)),
                ('IntresetedIn', models.ManyToManyField(to='AppSettings.intresetedin')),
                ('UserExpected', models.ManyToManyField(to='AppSettings.userexpected')),
                ('UserPreferance', models.ManyToManyField(to='AppSettings.userpreferance')),
                ('UserProfession', models.ManyToManyField(to='AppSettings.userprofession')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'USER PROFILE',
                'verbose_name_plural': 'USER PROFILE',
            },
        ),
    ]
