# Generated by Django 4.2.2 on 2023-11-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
    ]
