# Generated by Django 4.2.2 on 2023-11-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0003_remove_user_profile_userpreferance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
