# Generated by Django 4.2.2 on 2023-11-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0006_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='userbanner/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile/'),
        ),
    ]
